export const tableHeadList = [
  "ردیف",
  "شماره درس",
  "عنوان درس",
  "واحد",
  "گروه",
  "وضعیت",
  "وضعیت کلاس",
];
export const tableBodyList = [
  {
    subjectNumber: 100231011,
    subjectTitle: "علم مواد",
    subjectUnit: 3,
    subjectClassNumber: 1,
    subjectStatus: "",
    classStatus: "ارسال نشده",
  },
  {
    subjectNumber: 100231031,
    subjectTitle: "کارگاه ریخته گری و آهنگری",
    subjectUnit: 1,
    subjectClassNumber: 1,
    subjectStatus: "",
    classStatus: "ارسال نشده",
  },
  {
    subjectNumber: 120631801,
    subjectTitle: "انگلیسی تخصصی",
    subjectUnit: 2,
    subjectClassNumber: 2,
    subjectStatus: "",
    classStatus: "ارسال نشده",
  },
  {
    subjectNumber: 140531012,
    subjectTitle: "ورزش 1 ( تربیت بدنی2)",
    subjectUnit: 2,
    subjectClassNumber: 22,
    subjectStatus: "",
    classStatus: "ارسال نشده",
  },
  {
    subjectNumber: 230332501,
    subjectTitle: "کارافرینی 1",
    subjectUnit: 2,
    subjectClassNumber: 7,
    subjectStatus: "",
    classStatus: "ارسال نشده",
  },
  {
    subjectNumber: 320231111,
    subjectTitle: "ترمودینامیک 2",
    subjectUnit: 3,
    subjectClassNumber: 1,
    subjectStatus: "",
    classStatus: "ارسال نشده",
  },
  {
    subjectNumber: 320231131,
    subjectTitle: "مکانیک سیالات 1",
    subjectUnit: 3,
    subjectClassNumber: 1,
    subjectStatus: "",
    classStatus: "ارسال نشده",
  },
  {
    subjectNumber: 320231641,
    subjectTitle: "مقاومت مصالح 2",
    subjectUnit: 3,
    subjectClassNumber: 1,
    subjectStatus: "",
    classStatus: "ارسال نشده",
  },
];
